### ISSUE TITLE
Error reading XML file

### ISSUE THREAD

**Issue by opatrascoiu** [dmn-tck/tck#299]
Hi,

I am getting an exception when reading the latest version of the test cases files (file 0083-feel-unicode-test-01) see below. The cause is the commented out tests for substring.

Raised this issue to make sure we don't forget to investigate.

javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 118; columnNumber: 52; An invalid XML character (Unicode: 0xd83d) was found in the comment.]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:563)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:249)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:204)
	at org.omg.dmn.tck.marshaller.TckMarshallingHelper.load(TckMarshallingHelper.java:36)
	at org.omg.dmn.tck.runner.junit4.DmnTckRunner.<init>(DmnTckRunner.java:57)
	at org.omg.dmn.tck.runner.junit4.DmnTckSuite.<init>(DmnTckSuite.java:80)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.xml.sax.SAXParseException; lineNumber: 118; columnNumber: 52; An invalid XML character (Unicode: 0xd83d) was found in the comment.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1438)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.scanComment(XMLScanner.java:789)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanComment(XMLDocumentFragmentScannerImpl.java:1039)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2985)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
	... 20 more
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentLinkedQueue.checkNotNull(ConcurrentLinkedQueue.java:914)
	at java.util.concurrent.ConcurrentLinkedQueue.offer(ConcurrentLinkedQueue.java:327)
	at java.util.concurrent.ConcurrentLinkedQueue.add(ConcurrentLinkedQueue.java:297)
	at org.junit.runner.Description.addChild(Description.java:182)
	at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:352)
	at com.intellij.junit4.JUnit4IdeaTestRunner.getDescription(JUnit4IdeaTestRunner.java:78)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

Process finished with exit code -2

**Comment by tarilabs** [comment]
Which JDK are you running this on, please?

I am asking as both on my local machine (JDK8) and Travis CI does not exhibit this issue despite I confirmed they do pass through 
```
at org.omg.dmn.tck.marshaller.TckMarshallingHelper.load(TckMarshallingHelper.java:36)
at org.omg.dmn.tck.runner.junit4.DmnTckRunner.(DmnTckRunner.java:57)
at org.omg.dmn.tck.runner.junit4.DmnTckSuite.(DmnTckSuite.java:80)
```

I can sure move the commented-out tests in a non-compliant folder if this is causing troubles, but was worthy to ask this question to try understand if it's a local problem or environment problem, first.

**Comment by opatrascoiu** [comment]
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

on Windows. Investigating ...

**Comment by opatrascoiu** [comment]
The reported error

`[org.xml.sax.SAXParseException; lineNumber: 118; columnNumber: 52; An invalid XML character (Unicode: 0xd83d) was found in the comment.]`

is valid, based on the specification of the the XML comments. The allowed set of characters comments is 

`Char	   ::=   	#x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]	/* any Unicode character, excluding the surrogate blocks, FFFE, and FFFF. */`

See https://www.w3.org/TR/REC-xml/#sec-comments).

Not sure why the error is not reported in other envs.

**Comment by tarilabs** [comment]
> The reported error [...] is valid
> Not sure why the error is not reported in other envs.

I do not concur with these statements because:
As based by your stacktrace SAX Parser error, it is complaining about 0xd83d on line 118 of the 0083-feel-unicode-test-01.xml file:
https://github.com/dmn-tck/tck/blob/0838e12661ba13ca6122d87cc185b66861a78ed3/TestCases/compliance-level-3/0083-feel-unicode/0083-feel-unicode-test-01.xml#L118

The only way the grinning face emoji 😀 would end up parsed as `0xD83D` (followed by `0xDE00`) is when based on UTF-16
ref: https://www.compart.com/en/unicode/U+1F600
while the file is UTF-8 encoded as in the prolog:
https://github.com/dmn-tck/tck/blob/0838e12661ba13ca6122d87cc185b66861a78ed3/TestCases/compliance-level-3/0083-feel-unicode/0083-feel-unicode-test-01.xml#L1

So with proper UTF-8 grinning face emoji 😀 would end would end up as: `0xF0 0x9F 0x98 0x80`, valid.

Anyhow, I will raise an immediately merge a PR to rewrite the comment content to avoid troubles to parser which allegedly are ignoring the .xml xml prolog file encoding directive.

**Comment by opatrascoiu** [comment]
I tried to force the encoding to UTF-8 same errors.The buttom line is the file was incorrect (incorrect encoding). 

Thanks for fixing it.

Just curious, was the error reported by Travis CI?

**Comment by tarilabs** [comment]
> The bottom line is the file was incorrect (incorrect encoding).
> Thanks for fixing it.

I stand by the motivation detailed in UTF-8 Vs UTF-16 encoding I detailed in https://github.com/dmn-tck/tck/issues/299#issuecomment-492657711 and I don't think I fixed something, we just circumvented the problem for an environment which in my perspective is not respecting the xml prolog, ..or maybe Git on Windows is playing a role here in messing with the encoding? Just an idea..

> was the error reported by Travis CI?

No error on Travis CI, as mentioned https://github.com/dmn-tck/tck/issues/299#issuecomment-491599490
You can also double-verify by checking on the little Travis icons near commits or on the main Travis page.

**Comment by opatrascoiu** [comment]
Replacing manually the characters with UTF-8 encoding works. For example,

```
            <expected>
                <value xsi:type="xsd:string">\0xF0\0x9F\0x98\0x80</value>
            </expected>
```
We should probably use the UTF-8 encoding for this kind of characters to avoid issues like this. After all, the encoding at the top of the file is UTF-8.

**Comment by tarilabs** [comment]
Cool idea!
But for xml we should escape it with the `&#x1234;` markup escape sequence, I mean using the `&#` way not with `\0x`, do you agree or have I missed something, please?

**Comment by opatrascoiu** [comment]
Even better with &#x1234 :)
